/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import { HttpClient, HttpHeaders, HttpResponse as AngularHttpResponse } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  AuthResponse,
  HelloResponse,
  LoginDto,
  ProfileResponse,
  RefreshTokenDto,
  RegisterDto,
  UpdateProfileDto,
} from './model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class APIGatewayService {
  private readonly http = inject(HttpClient);
  getHello<TData = HelloResponse>(options?: HttpClientBodyOptions): Observable<TData>;
  getHello<TData = HelloResponse>(options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
  getHello<TData = HelloResponse>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  getHello<TData = HelloResponse>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/v1/hello`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/v1/hello`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/api/v1/hello`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  authLogin<TData = AuthResponse>(
    loginDto?: LoginDto,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  authLogin<TData = AuthResponse>(
    loginDto?: LoginDto,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  authLogin<TData = AuthResponse>(
    loginDto?: LoginDto,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  authLogin<TData = AuthResponse>(
    loginDto?: LoginDto,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/v1/auth/login`, loginDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/v1/auth/login`, loginDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/v1/auth/login`, loginDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  authRegister<TData = void>(
    registerDto?: RegisterDto,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  authRegister<TData = void>(
    registerDto?: RegisterDto,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  authRegister<TData = void>(
    registerDto?: RegisterDto,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  authRegister<TData = void>(
    registerDto?: RegisterDto,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/v1/auth/register`, registerDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/v1/auth/register`, registerDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/v1/auth/register`, registerDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  authRefresh<TData = AuthResponse>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  authRefresh<TData = AuthResponse>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  authRefresh<TData = AuthResponse>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  authRefresh<TData = AuthResponse>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/v1/auth/refresh`, refreshTokenDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/v1/auth/refresh`, refreshTokenDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/v1/auth/refresh`, refreshTokenDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  authLogout<TData = void>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  authLogout<TData = void>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  authLogout<TData = void>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  authLogout<TData = void>(
    refreshTokenDto?: RefreshTokenDto,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/v1/auth/logout`, refreshTokenDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/v1/auth/logout`, refreshTokenDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/api/v1/auth/logout`, refreshTokenDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  usersMeGet<TData = ProfileResponse>(options?: HttpClientBodyOptions): Observable<TData>;
  usersMeGet<TData = ProfileResponse>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  usersMeGet<TData = ProfileResponse>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  usersMeGet<TData = ProfileResponse>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/v1/users/me`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/v1/users/me`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/api/v1/users/me`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  usersMePatch<TData = ProfileResponse>(
    updateProfileDto?: UpdateProfileDto,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  usersMePatch<TData = ProfileResponse>(
    updateProfileDto?: UpdateProfileDto,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  usersMePatch<TData = ProfileResponse>(
    updateProfileDto?: UpdateProfileDto,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  usersMePatch<TData = ProfileResponse>(
    updateProfileDto?: UpdateProfileDto,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.patch<TData>(`/api/v1/users/me`, updateProfileDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.patch<TData>(`/api/v1/users/me`, updateProfileDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.patch<TData>(`/api/v1/users/me`, updateProfileDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}
