/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * API Gateway
 * The API Gateway entry point description
 * OpenAPI spec version: 1.0
 */
import type { HelloResponseServices } from './helloResponseServices';

export interface HelloResponse {
  message?: string;
  services?: HelloResponseServices;
}
