/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export type AuthResponseData = {
  accessToken?: string;
  refreshToken?: string;
  user?: User;
};
