/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * API Gateway
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface ProfileResponse {
  statusCode?: number;
  message?: string;
  data?: User;
}
